// Copyright (C) 2026, LibreDarwin
// SPDX-License-Identifier: BSD-3-Clause
//
// Generated by tools/xct-assertions.py. Do not edit by hand.
//
// The failure text for every assertion primitive. Each entry is keyed by
// (assertion type, format index); the index distinguishes the "the assertion did
// not hold" message from the "the expression raised" one, and the throws family
// adds further indices for the different ways it can go wrong.
//
// The argument lists here are not decorative. The generated macros pass exactly
// these expressions, in this order, to _XCTFailureDescription, and the generator
// refuses to emit if a conversion count and its argument count disagree.

#import "XCTestInternal.h"

NSString *_XCTFailureFormat(_XCTAssertionType assertionType, NSUInteger formatIndex)
{
    switch (assertionType) {
        case _XCTAssertion_Fail:
            if (formatIndex == 0) {
                return @"XCTFail failed";
            }
            break;
        case _XCTAssertion_Nil:
            if (formatIndex == 0) {
                return @"XCTAssertNil failed: (%@) is not nil: (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertNil threw an exception evaluating (%@): %@";
            }
            break;
        case _XCTAssertion_NotNil:
            if (formatIndex == 0) {
                return @"XCTAssertNotNil failed: (%@) is nil";
            }
            if (formatIndex == 1) {
                return @"XCTAssertNotNil threw an exception evaluating (%@): %@";
            }
            break;
        case _XCTAssertion_EqualObjects:
            if (formatIndex == 0) {
                return @"XCTAssertEqualObjects failed: (%@) is not equal to (%@): (%@) != (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertEqualObjects threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_NotEqualObjects:
            if (formatIndex == 0) {
                return @"XCTAssertNotEqualObjects failed: (%@) is equal to (%@): (%@) == (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertNotEqualObjects threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_Equal:
            if (formatIndex == 0) {
                return @"XCTAssertEqual failed: (%@) is not equal to (%@): (%@) != (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertEqual threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_NotEqual:
            if (formatIndex == 0) {
                return @"XCTAssertNotEqual failed: (%@) is equal to (%@): (%@) == (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertNotEqual threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_EqualWithAccuracy:
            if (formatIndex == 0) {
                return @"XCTAssertEqualWithAccuracy failed: (%@) is not within (%@) of (%@): (%@) != (%@) +/- (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertEqualWithAccuracy threw an exception comparing (%@) with (%@) within (%@): %@";
            }
            break;
        case _XCTAssertion_NotEqualWithAccuracy:
            if (formatIndex == 0) {
                return @"XCTAssertNotEqualWithAccuracy failed: (%@) is within (%@) of (%@): (%@) == (%@) +/- (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertNotEqualWithAccuracy threw an exception comparing (%@) with (%@) within (%@): %@";
            }
            break;
        case _XCTAssertion_GreaterThan:
            if (formatIndex == 0) {
                return @"XCTAssertGreaterThan failed: (%@) is not greater than (%@): (%@) <= (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertGreaterThan threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_GreaterThanOrEqual:
            if (formatIndex == 0) {
                return @"XCTAssertGreaterThanOrEqual failed: (%@) is not greater than or equal to (%@): (%@) < (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertGreaterThanOrEqual threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_LessThan:
            if (formatIndex == 0) {
                return @"XCTAssertLessThan failed: (%@) is not less than (%@): (%@) >= (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertLessThan threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_LessThanOrEqual:
            if (formatIndex == 0) {
                return @"XCTAssertLessThanOrEqual failed: (%@) is not less than or equal to (%@): (%@) > (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertLessThanOrEqual threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_True:
            if (formatIndex == 0) {
                return @"XCTAssertTrue failed: (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertTrue threw an exception evaluating (%@): %@";
            }
            break;
        case _XCTAssertion_False:
            if (formatIndex == 0) {
                return @"XCTAssertFalse failed: (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertFalse threw an exception evaluating (%@): %@";
            }
            break;
        case _XCTAssertion_Throws:
            if (formatIndex == 0) {
                return @"XCTAssertThrows failed: (%@) did not throw an exception";
            }
            break;
        case _XCTAssertion_ThrowsSpecific:
            if (formatIndex == 0) {
                return @"XCTAssertThrowsSpecific failed: (%@) threw an exception, but not of type %@ (expected %@): %@";
            }
            if (formatIndex == 1) {
                return @"XCTAssertThrowsSpecific failed: (%@) did not throw an exception of type %@";
            }
            break;
        case _XCTAssertion_ThrowsSpecificNamed:
            if (formatIndex == 0) {
                return @"XCTAssertThrowsSpecificNamed failed: (%@) threw %@ (expected %@) with name \"%@\", but it was named \"%@\": %@";
            }
            if (formatIndex == 1) {
                return @"XCTAssertThrowsSpecificNamed failed: (%@) threw a %@ named \"%@\", but it was expected to be a %@ named \"%@\": %@";
            }
            if (formatIndex == 2) {
                return @"XCTAssertThrowsSpecificNamed failed: (%@) did not throw an exception of type %@ with name \"%@\"";
            }
            if (formatIndex == 3) {
                return @"XCTAssertThrowsSpecificNamed failed: (%@) did not throw at all; expected %@ named \"%@\"";
            }
            break;
        case _XCTAssertion_NoThrow:
            if (formatIndex == 0) {
                return @"XCTAssertNoThrow failed: (%@) threw an exception: %@";
            }
            break;
        case _XCTAssertion_NoThrowSpecific:
            if (formatIndex == 0) {
                return @"XCTAssertNoThrowSpecific failed: (%@) threw an exception of type %@ (expected %@): %@";
            }
            break;
        case _XCTAssertion_NoThrowSpecificNamed:
            if (formatIndex == 0) {
                return @"XCTAssertNoThrowSpecificNamed failed: (%@) threw %@ (expected %@) with name \"%@\", but it was named \"%@\": %@";
            }
            break;
        case _XCTAssertion_Identical:
            if (formatIndex == 0) {
                return @"XCTAssertIdentical failed: (%@) is not identical to (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertIdentical threw an exception comparing (%@) with (%@): %@";
            }
            break;
        case _XCTAssertion_NotIdentical:
            if (formatIndex == 0) {
                return @"XCTAssertNotIdentical failed: (%@) is identical to (%@)";
            }
            if (formatIndex == 1) {
                return @"XCTAssertNotIdentical threw an exception comparing (%@) with (%@): %@";
            }
            break;
        default:
            break;
    }
    return @"";
}
