#!/bin/bash
# Copyright (C) 2026, LibreDarwin
# SPDX-License-Identifier: BSD-3-Clause
#
# Regenerates src/xctest/.clangd from the SDK the build is configured to use.
#
# The committed .clangd names an absolute SDK path, because clangd does not
# expand environment variables in CompileFlags and cannot read the Makefile.
# That means the committed copy is correct for whoever wrote it and points at
# nothing for everyone else, where the symptom is every header cascading into
# "unknown type name NSObject".
#
# So the file is generated, not hand-maintained: run this after changing SDK.
#   SDK=/path/to/MacOSX.Internal.sdk make clangd-config
#
# The compiler remains the source of truth for this project. See
# tools/check-headers.sh, which is what actually proves the headers are good.

set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/src/xctest/.clangd"

# Matches the Makefile's default so a bare run reproduces the committed file.
SDK=${SDK:-/Users/sunneva/xnuports-root/devel/xcode-tools/build/release/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.Internal.sdk}

if [ ! -d "$SDK" ]; then
    echo "gen-clangd-config: no such SDK: $SDK" >&2
    echo "  pass the one to use: SDK=/path/to/MacOSX.sdk $0" >&2
    exit 1
fi

tmp="$out.tmp.$$"
trap 'rm -f "$tmp"' EXIT

# Every entry has to be a single well-formed argument. One malformed entry
# makes clangd discard the whole CompileFlags list, which looks exactly like
# the file being ignored.
cat >"$tmp" <<EOF
# clangd configuration for the XCTest framework sources (src/xctest).
#
# GENERATED by tools/gen-clangd-config.sh -- edit that script, not this file.
# Regenerate with: SDK=<path to MacOSX.Internal.sdk> make clangd-config
#
# The public headers are consumed framework-style -- <XCTest/XCTestDefines.h> --
# so that client code compiles unmodified against either this framework or
# Apple's. That only resolves when the header root is on the include path,
# which the Makefile supplies via -Isrc/xctest/include.
#
# Two things this has to get right, both learned the hard way:
#
#  * Include paths are resolved against the LSP's working directory (the repo
#    root), NOT against this file's directory. So the Makefile's spelling has
#    to be repeated verbatim here; a "include" relative to src/xctest silently
#    resolves to a nonexistent repo-root/include.
#
#  * clangd must be pointed at the Internal SDK. Left on the host macOS SDK it
#    cannot see <Foundation/Foundation.h> at all, and every header cascades
#    into "unknown type name NSObject".
#
#  * Keep every entry a single well-formed argument. One bad entry (e.g. a
#    -target= spelling clangd's flag table rejects) makes clangd discard the
#    entire CompileFlags list, which looks exactly like this file being ignored.
#
# The compiler remains the source of truth: \`make check-headers\`.
CompileFlags:
  Compiler: clang
  Add:
    - -Isrc/xctest/include
    - -fobjc-arc
    - -Wall
    - -isysroot=$SDK
EOF

mv "$tmp" "$out"
trap - EXIT
echo "gen-clangd-config: wrote $out"
echo "  SDK: $SDK"
