#!/bin/bash
# Copyright (C) 2026, LibreDarwin
# SPDX-License-Identifier: BSD-3-Clause
#
# Regenerates the committed .clangd files from the SDK the build is configured
# to use. There are two, one at the root of each framework's sources: src/xctest
# and src/xctestcore. clangd reads the nearest .clangd above a file and stops
# there -- it does not merge two -- so each source root needs its own, complete
# config, and a framework whose root has none gets no include paths at all.
#
# The committed files name absolute paths, because clangd does not expand
# environment variables in CompileFlags and cannot read the Makefile. That means
# the committed copies are correct for whoever wrote them and point at nothing
# for everyone else, where the symptom is every header cascading into "unknown
# type name NSObject".
#
# So the files are generated, not hand-maintained: run this after changing SDK.
#   SDK=/path/to/MacOSX.Internal.sdk make clangd-config
#
# The compiler remains the source of truth for this project. See
# tools/check-headers.sh, which is what actually proves the headers are good.

set -eu

root=$(cd "$(dirname "$0")/.." && pwd)

# Removes the file write_clangd is mid-way through, if the script dies early.
tmp=
trap 'rm -f "$tmp"' EXIT

# Matches the Makefile's default so a bare run reproduces the committed files.
SDK=${SDK:-/Users/sunneva/xnuports-root/devel/xcode-tools/build/release/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.Internal.sdk}

if [ ! -d "$SDK" ]; then
    echo "gen-clangd-config: no such SDK: $SDK" >&2
    echo "  pass the one to use: SDK=/path/to/MacOSX.sdk $0" >&2
    exit 1
fi

# write_clangd <source-root> <framework> <example-header> <include-flags...>
#
# The include flags are the ones the Makefile passes for that framework, spelled
# the same way, so an editor resolves exactly what the build does.
write_clangd() {
    directory="$1"
    framework="$2"
    example="$3"
    shift 3

    out="$root/$directory/.clangd"
    tmp="$out.tmp.$$"
    {
        cat <<EOF
# clangd configuration for the $framework framework sources ($directory).
#
# GENERATED by tools/gen-clangd-config.sh -- edit that script, not this file.
# Regenerate with: SDK=<path to MacOSX.Internal.sdk> make clangd-config
#
# The public headers are consumed framework-style, as <$framework/$example>,
# so that client code compiles unmodified against either this framework or
# Apple's. That only resolves when the header root is on the include path,
# which the Makefile supplies via -I<checkout>/$directory/include; the -I
# entries below are that path, made absolute.
#
# Three things this has to get right, all learned the hard way:
#
#  * Include paths must be absolute. clangd runs the compile command with its
#    working directory set to the file's own directory, not the checkout, so a
#    relative -I resolves there and silently points at nothing. The generator
#    expands every -I from the checkout root.
#
#  * clangd must be pointed at the Internal SDK. Left on the host macOS SDK it
#    cannot see <Foundation/Foundation.h> at all, and every header cascades
#    into "unknown type name NSObject". The spelling matters too: it has to be
#    -isysroot<path>, joined with no "=". Written -isysroot=<path> instead,
#    clang takes the value to be "=<path>" and reports "no such sysroot
#    directory", which loses Foundation exactly the same way.
#
#  * Keep every entry a single well-formed argument. One bad entry (e.g. a
#    -target= spelling clangd's flag table rejects) makes clangd discard the
#    entire CompileFlags list, which looks exactly like this file being ignored.
#
# The compiler remains the source of truth: \`make check-headers\`.
CompileFlags:
  Compiler: clang
  Add:
EOF
        for flag in "$@"; do
            printf '    - %s\n' "$flag"
        done
    } > "$tmp"
    mv "$tmp" "$out"
    echo "gen-clangd-config: wrote $out"
}

# XCTest reads its include root. src/xctest has no implementation files of its own
# any more -- it is the re-exporting shim -- but it still holds the public headers,
# and that is the include root a client needs, so the config stays.
#
# XCTestCore reads three roots and needs all three. Its own include root, the
# source root beside it because it declares a private header
# (XCTestCoreFoundationCompat.h) next to the implementations rather than under
# include/, and the public root, because every implementation here is declared in
# <XCTest/...> and imports itself that way. Without the third, clangd reports
# "file not found" for the framework's own headers in all 19 files -- and unlike
# the Include-path-absolute trap above, that one is silent in the sense that the
# header simply is not found, with nothing pointing at a flag being wrong.
#
# -fblocks for XCTestCore: one property in XCTestConfiguration.h is a block, so an
# editor without it cannot parse that header. Every -I is absolute (see above).
write_clangd src/xctest XCTest XCTestDefines.h \
    "-I$root/src/xctest/include" -fobjc-arc -Wall "-isysroot$SDK"

write_clangd src/xctestcore XCTestCore XCTestCore.h \
    "-I$root/src/xctestcore/include" "-I$root/src/xctestcore" "-I$root/src/xctest/include" \
    -fobjc-arc -fblocks -Wall "-isysroot$SDK"

echo "gen-clangd-config: SDK: $SDK"
